### ISSUE TITLE
Add Payload to Psyllid RUN Requests

### ISSUE THREAD

**Issue by nsoblath** [project8/psyllid#24]
The following should be used as the payload for RUN requests received by Psyllid:

```json
payload: {
    "filename": "[filename]",
    "duration": [ms],
    "center-freq": [Hz],
    "freq-range": [Hz]
}
```

All parameters will be optional.

**Comment by nsoblath** [comment]
As of commit 02d74c4815fe0d0656bb6592bf6854a622db067b the filename, description, and duration can be set from the payload of the dripline run cmd.

**Comment by nsoblath** [comment]
@claessens: On slack the other day we discussed setting the center frequency and frequency range in Psyllid from the payload of the run request, as in my example above.  However, I don't think this is going to work.  It's not particularly natural to get that information from where the request is handled to the file-writing class.  It could be done, but I'd rather see if there's a better solution on the dragonfly side.

There's also one additional complication that we didn't consider: those parameters need to be set for each channel.  In Psyllid, now, the different channels (or "streams" as Psyllid calls them) are identified by an integer ID number.  The ID number is assigned when the stream is added.  For the most part, that will be when Psyllid starts.  

So first we need a way to tell the dragonfly service which ROACH channel corresponds to which Psyllid stream.  We might need to do that by hand, but I'll think about that one some more and let me know if you have any ideas.

Then we need a way to set the CF and frequency range for a given channel.  I could take care of that on the Psyllid side with functions that accept SET and GET requests for parameters in the Psyllid DAQ system.  The routing keys would be something like `[psyllid queue].daq-param.0_strw.cf`, and the value would be in MHz.  `0_strw` indicates the processor called `strw` in stream 0.  Is there a way to have the ROACH DAQ service send messages to both the ROACH and Psyllid whenever the parameters are set by the user?

**Comment by cclaessens** [comment]
Yes we can do the setting of the central frequency with dragonfly. Also cross talking between services is no problem. 
Actually, the start_timed_run method currently
- checks whether psyllid is running
- check whether the psyllid status is idle
- check the roach and its service is running and whether the roach has been configured and calibrated
- set the duration and the filename in psyllid
- tell psyllid to start the run

For the central frequency I would add that start_timed_run gets the central frequency of the roach service and sets it in psyllid.

I am not totally sure what the best 3 channel solution would be.
How are we going to tell psyllid whether to start a run with only one channel or all 3 of them simultaneously? Would psyllid have different requests for this or will this information be passes in the payload?

In addition to the run name and the run duration a string with channel names could be a requirement for calling start_timed_run. The dragonfly psyllid service would then know which psyllid stream corresponds to the roach channels and which sets and requests to send to psyllid.
I don't think that the channel-stream setup is sth that needs to be changeable during operation and therefore could be set in the config files. The channels can only differ by the central frequency.

Why do we need to set the frequency range? Its always +/- 50MHz and could be set as a consequence of the central frequency in psyllid.

**Comment by cclaessens** [comment]
I only just saw that there is a request receiver to add and remove streams while psyllid is already running.
Why do you want to give the streams IDs rather than a name? 
And what happens if you try to add a stream and the interface is already used by another stream?
I guess we want to include the removal and addition of streams in dragonfly?

I think the easiest way to do this is to add the possibility to request all stream ids with the corresponding network interfaces from psyllid. During startup of the dragonfly services and after adding or removing streams, the dragonfly psyllid interface could then request all channels and their interfaces and the streams and their interfaces and link channels and streams together.
With this you would have everything covered.

You could also just stick to fixed stream names and interfaces in psyllid. A dragonfly method to change a stream configuration could be sth like: change_psyllid_preset channel='a' which would remove the stream called stream_eth1 and add a new one with the same name (and same interface) but a different preset.

The set central frequency command could also not only send the new frequency to the roach channel but also to the corresponding psyllid stream.

**Comment by nsoblath** [comment]
We want to have the frequency range set because, while for right now it will be the same, that's not necessarily always going to be the case.  Psyllid handles CF and frequency range in the same way, and they have the obvious relationship to one another in their physical meaning, so it makes sense to treat them similarly from the controls perspective.

You're right that it makes sense to use a name for stream identification, instead of a number.  I had it as a number because I had initially used a vector to store the streams, and I just returned the position in the vector as the stream ID.  But then I realized that one might want to add or remove streams, and that would cause the stream ID to change for a given stream if I was using a vector.  So I changed to using a map, instead, but I still stuck with the integer ID number.  But it's makes more sense to go with names, and it fits better with how other similar things are configured (e.g. nodes in Psyllid; processors in Katydid).

I don't know what will happen if two streams listen on the same network interface.  Streams do not check with one another about which interface they're listening on.  There's no global control over that in the FPA code, either.  So I'm not really sure what would happen.  I will document that the consequences of doing that are undefined.  And I'll look for a good way to protect against it happening accidentally.  We can use a standard where we name streams after the network interface they use.  That's just an administrative barrier, but it might suffice for now.

Psyllid will record one or more channels of data based on how it's configured.  If it's setup with 2 streams, then 2 streams will be recorded, for example.  If one wants to switch the number of streams, then the streams will need to be added or removed as necessary.

**Comment by nsoblath** [comment]
Center frequency and frequency range are now settable parameters in streaming_writer and egg_writer, but they are not included in the run command payload.  They're also in MHz, instead of Hz as originally posted.

**Comment by cclaessens** [comment]
Do we want to change that to Hz instead of MHz? If you set the central frequency for the roach to an integer number in MHz often the frequency cannot be set precisely to that number. The actual central frequency is returned and we probably want to set the central frequency in psyllid as close to the actual central frequency as possible.
