### ISSUE TITLE
Event writer logic

### ISSUE THREAD

**Issue by sboeser** [project8/psyllid#3]
Hi Noah,
Christine and me have been trying to understand the logic in the `egg_writer.cc`. In lines 137-140 you have some logic to advance that time stream till you hit the `start_id` that is obtained from the event builder. The condition to stop advancing is

    while( t_time_id < t_start_id ) {

However, inside the loop, you re-read the `t_start_id` from the event builder *blob* (which should stay constant), instead of updating the `t_time_id` from the newly obtained `time_stream` *blob*. 

Are we missing something?

P.S: I'm sure there is a more appropriate name than *blob* for the thingy that is returned by `instream< x >().get()`... ?

**Comment by nsoblath** [comment]
Hi Sebastian and Christine,

You're right that that's a bug.  However, the version of the code you're looking at (I assume either the develop or master branch) shouldn't be used.  I've been working in the feature/firstversion branch.  I've been a bit lazy with my git branching behavior since I was the only one working on Psyllid.  Now that it has more attention I'll make sure features get back to the develop branch more often.

You'll find the egg writer in the `daq` directory.  The way the egg writer works has changed pretty significantly to allow acquisition on multiple channels.  However, there's still a section that attempts to line up the two streams if they're mismatched (starting at line 191 or so), and I think it's correct in this case.

Of course I can't promise it's bug-free, so I'm glad it's getting some review :-)

Regarding what to call the _blob_, the `get()` function actually just returns the "command" for the stream, which is essentially its status at that point in the stream.  But it first advances the iterator on the stream.  The stream is essentially a circular buffer of data objects.  The processor has an iterator that points to one particular data object at any given time.  That can be accessed with the `data()` function.

**Comment by nsoblath** [comment]
I'll assume this issue is resolved for now, but please reopen if there's still a problem.
